----------------------------------------------------------------------------------------------------
[INFO] - 2021-12-04 07:03:42,222

Source log file: /usr/lib/python3.9/site-packages/django/utils/autoreload.py line: 637

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2022-02-06 11:56:29,935

Source log file: /usr/lib/python3.9/site-packages/django/utils/autoreload.py line: 643

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2022-06-23 11:21:51,672

Source log file: /usr/lib/python3.10/site-packages/django/utils/autoreload.py line: 677

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2022-06-23 12:14:52,849

Source log file: /usr/lib/python3.10/site-packages/django/utils/autoreload.py line: 677

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2022-06-23 12:19:34,241

Source log file: /usr/lib/python3.10/site-packages/django/utils/autoreload.py line: 266

/root/magic_packet/src/backend/backend/settings.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2022-06-23 12:19:34,537

Source log file: /usr/lib/python3.10/site-packages/django/utils/autoreload.py line: 677

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2022-06-23 12:20:07,677

Source log file: /usr/lib/python3.10/site-packages/django/utils/autoreload.py line: 677

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2022-06-23 12:21:03,141

Source log file: /usr/lib/python3.10/site-packages/django/utils/autoreload.py line: 266

/root/magic_packet/src/backend/backend/settings.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2022-06-23 12:21:03,488

Source log file: /usr/lib/python3.10/site-packages/django/utils/autoreload.py line: 677

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2022-06-23 12:22:45,479

Source log file: /usr/lib/python3.10/site-packages/django/utils/autoreload.py line: 677

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2022-06-23 12:24:16,857

Source log file: /usr/lib/python3.10/site-packages/django/utils/autoreload.py line: 266

/root/magic_packet/src/backend/backend/urls.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2022-06-23 12:24:17,215

Source log file: /usr/lib/python3.10/site-packages/django/utils/autoreload.py line: 677

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2022-06-23 12:25:32,263

Source log file: /usr/lib/python3.10/site-packages/django/utils/autoreload.py line: 266

/root/magic_packet/src/backend/sendpacket/sendpacket.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2022-06-23 12:25:32,625

Source log file: /usr/lib/python3.10/site-packages/django/utils/autoreload.py line: 677

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[WARNING] - 2022-06-23 12:26:17,083

Source log file: /usr/lib/python3.10/site-packages/django/utils/log.py line: 241

Not Found: /api/sendpacket/
----------------------------------------------------------------------------------------------------
[WARNING] - 2022-06-23 12:26:17,084

Source log file: /usr/lib/python3.10/site-packages/django/core/servers/basehttp.py line: 187

"POST /api/sendpacket/ HTTP/1.0" 404 179
----------------------------------------------------------------------------------------------------
[ERROR] - 2022-06-23 12:26:28,648

Source log file: /root/magic_packet/src/backend/sendpacket/views.py line: 17

{'macaddr': 'dc:a6:32:a7:1e:bd'}
----------------------------------------------------------------------------------------------------
[ERROR] - 2022-06-23 12:26:28,648

Source log file: /root/magic_packet/src/backend/sendpacket/sendpacket.py line: 30

Traceback (most recent call last):
  File "/root/magic_packet/src/backend/sendpacket/sendpacket.py", line 21, in sendpacket
    packet = b'\xff' * 6 + struct.pack('BBBBBB', *([int(octet, 16) for octet in macaddr.split(':')]))
AttributeError: 'dict' object has no attribute 'split'

----------------------------------------------------------------------------------------------------
[INFO] - 2022-06-23 12:26:28,649

Source log file: /usr/lib/python3.10/site-packages/django/core/servers/basehttp.py line: 187

"POST /api/sendpacket HTTP/1.0" 200 19
----------------------------------------------------------------------------------------------------
[INFO] - 2022-06-23 12:31:09,657

Source log file: /usr/lib/python3.10/site-packages/django/utils/autoreload.py line: 266

/root/magic_packet/src/backend/sendpacket/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2022-06-23 12:31:10,016

Source log file: /usr/lib/python3.10/site-packages/django/utils/autoreload.py line: 677

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[WARNING] - 2022-06-23 12:31:12,761

Source log file: /usr/lib/python3.10/site-packages/django/utils/log.py line: 241

Bad Request: /api/sendpacket
----------------------------------------------------------------------------------------------------
[WARNING] - 2022-06-23 12:31:12,761

Source log file: /usr/lib/python3.10/site-packages/django/core/servers/basehttp.py line: 187

"POST /api/sendpacket HTTP/1.0" 400 2
----------------------------------------------------------------------------------------------------
[INFO] - 2022-06-23 12:31:34,628

Source log file: /usr/lib/python3.10/site-packages/django/utils/autoreload.py line: 266

/root/magic_packet/src/backend/sendpacket/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2022-06-23 12:31:34,996

Source log file: /usr/lib/python3.10/site-packages/django/utils/autoreload.py line: 677

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2022-06-23 12:31:35,644

Source log file: /usr/lib/python3.10/site-packages/django/core/servers/basehttp.py line: 187

"POST /api/sendpacket HTTP/1.0" 200 20
